server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.104
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 20 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  activiti:
    # activiti default configuration
    #在activiti的默认配置中，process-definition-location-prefix 是指定activiti流程描述文件的前缀（即路径），
    #启动时，activiti就会去寻找此路径下的流程描述文件，并且自动部署；suffix 是一个String数组，表示描述文件的默    认后缀名，默认以上两种。
    database-schema-update: true #是否每次都更新数据库
    # 自动部署验证设置:true-开启（默认）、false-关闭
    check-process-definitions: false # activti是否自动部署
    process-definition-location-prefix: classpath:/processes/
    process-definition-location-suffixes: .bpmn
    #history-level: full
    db-history-used: true
    db-identity-used: false
  application:
    name: TATAINIYO
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.7:3306/projectdb?serverTimezone=UTC&nullCatalogMeansCurrent=true&allowMultiQueries=true
    password: 123456
    username: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置获取连接等待超时的时间
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
mybatis:
  type-aliases-package: com.activiti.tataainiyo.base,com.activiti.tataainiyo.demo
  mapper-locations: com/activiti/tataainiyo/mapper/**Mapper.xml
logging:
  level:
    com.activiti.tataainiyo.mapper : debug

